### ISSUE TITLE
Plugin breaks with PHP 8

### ISSUE THREAD

**Issue by ravewebdev** [pristas-peter/wp-graphql-gutenberg#100] opened 2021-04-28 16:23 UTC
We've encountered various issues with this plugin when running PHP 8 that do not appear when running PHP 7.

A user of our Next.js starter repo [pointed to the ivome/graphql-relay-php dependency](https://github.com/WebDevStudios/nextjs-wordpress-starter/issues/394#issuecomment-828059163) as a potential culprit.

One issue we've been able to replicate on several devices:
1. Add a paragraph block to a page with some text
2. Change WP to PHP 8
3. Query page: (this should work without error)
```
query MyQuery {
  page(id: "<ID>", idType: DATABASE_ID) {
    blocksJSON
  }
}
```
4. Edit paragraph block to set a custom font-size
5. Re-query page (it should throw an error this time) *
6. Change WP to PHP 7
7. Re-query page again (it should not throw an error now)

Error thrown when querying page:
```
{
  "errors": [
    {
      "debugMessage": "get_object_vars(): Argument #1 ($object) must be of type object, array given",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "page",
        "blocksJSON"
      ],
      "trace": [
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql-gutenberg/vendor/opis/json-schema/src/Validator.php",
          "line": 1792,
          "function": "get_object_vars(array(1))"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql-gutenberg/vendor/opis/json-schema/src/Validator.php",
          "line": 953,
          "call": "Opis\\JsonSchema\\Validator::validateObject(instance of stdClass, array(1), array(1), array(0), instance of Opis\\JsonSchema\\Schema, instance of stdClass, instance of Opis\\JsonSchema\\ValidationResult, null)"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql-gutenberg/vendor/opis/json-schema/src/Validator.php",
          "line": 519,
          "call": "Opis\\JsonSchema\\Validator::validateProperties(instance of stdClass, array(1), array(1), array(0), instance of Opis\\JsonSchema\\Schema, instance of stdClass, instance of Opis\\JsonSchema\\ValidationResult, null)"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql-gutenberg/vendor/opis/json-schema/src/Validator.php",
          "line": 332,
          "call": "Opis\\JsonSchema\\Validator::validateKeywords(instance of stdClass, array(1), array(1), array(0), instance of Opis\\JsonSchema\\Schema, instance of stdClass, instance of Opis\\JsonSchema\\ValidationResult)"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql-gutenberg/vendor/opis/json-schema/src/Validator.php",
          "line": 1915,
          "call": "Opis\\JsonSchema\\Validator::validateSchema(instance of stdClass, array(1), array(1), array(0), instance of Opis\\JsonSchema\\Schema, instance of stdClass, instance of Opis\\JsonSchema\\ValidationResult)"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql-gutenberg/vendor/opis/json-schema/src/Validator.php",
          "line": 953,
          "call": "Opis\\JsonSchema\\Validator::validateObject(instance of stdClass, instance of stdClass, array(1), array(0), instance of Opis\\JsonSchema\\Schema, instance of stdClass, instance of Opis\\JsonSchema\\ValidationResult, array(2))"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql-gutenberg/vendor/opis/json-schema/src/Validator.php",
          "line": 519,
          "call": "Opis\\JsonSchema\\Validator::validateProperties(instance of stdClass, instance of stdClass, array(0), array(0), instance of Opis\\JsonSchema\\Schema, instance of stdClass, instance of Opis\\JsonSchema\\ValidationResult, array(2))"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql-gutenberg/vendor/opis/json-schema/src/Validator.php",
          "line": 332,
          "call": "Opis\\JsonSchema\\Validator::validateKeywords(instance of stdClass, instance of stdClass, array(0), array(0), instance of Opis\\JsonSchema\\Schema, instance of stdClass, instance of Opis\\JsonSchema\\ValidationResult)"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql-gutenberg/vendor/opis/json-schema/src/Validator.php",
          "line": 97,
          "call": "Opis\\JsonSchema\\Validator::validateSchema(instance of stdClass, instance of stdClass, array(0), array(0), instance of Opis\\JsonSchema\\Schema, instance of stdClass, instance of Opis\\JsonSchema\\ValidationResult)"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql-gutenberg/src/Blocks/Block.php",
          "line": 145,
          "call": "Opis\\JsonSchema\\Validator::schemaValidation(instance of stdClass, instance of Opis\\JsonSchema\\Schema)"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql-gutenberg/src/Blocks/Block.php",
          "line": 177,
          "call": "WPGraphQLGutenberg\\Blocks\\Block::parse_attributes(array(5), array(14))"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql-gutenberg/src/Blocks/Block.php",
          "line": 25,
          "call": "WPGraphQLGutenberg\\Blocks\\Block::__construct(array(5), 15, array(36), 0, null)"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql-gutenberg/src/Schema/Types/InterfaceType/BlockEditorContentNode.php",
          "line": 36,
          "call": "WPGraphQLGutenberg\\Blocks\\Block::create_blocks(array(1), 15, array(36))"
        },
        {
          "call": "WPGraphQLGutenberg\\Schema\\Types\\InterfaceType\\BlockEditorContentNode::WPGraphQLGutenberg\\Schema\\Types\\InterfaceType\\{closure}(instance of WPGraphQL\\Model\\Post, array(0), instance of WPGraphQL\\AppContext, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql/src/Utils/InstrumentSchema.php",
          "line": 177,
          "function": "call_user_func(instance of Closure, instance of WPGraphQL\\Model\\Post, array(0), instance of WPGraphQL\\AppContext, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "call": "WPGraphQL\\Utils\\InstrumentSchema::WPGraphQL\\Utils\\{closure}(instance of WPGraphQL\\Model\\Post, array(0), instance of WPGraphQL\\AppContext, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql/src/Utils/InstrumentSchema.php",
          "line": 177,
          "function": "call_user_func(instance of Closure, instance of WPGraphQL\\Model\\Post, array(0), instance of WPGraphQL\\AppContext, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 624,
          "call": "WPGraphQL\\Utils\\InstrumentSchema::WPGraphQL\\Utils\\{closure}(instance of WPGraphQL\\Model\\Post, array(0), instance of WPGraphQL\\AppContext, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 550,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveFieldValueOrError(instance of GraphQL\\Type\\Definition\\FieldDefinition, instance of GraphQL\\Language\\AST\\FieldNode, instance of Closure, instance of WPGraphQL\\Model\\Post, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 1196,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveField(GraphQLType: Page, instance of WPGraphQL\\Model\\Post, instance of ArrayObject(1), array(2))"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 1146,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeFields(GraphQLType: Page, instance of WPGraphQL\\Model\\Post, array(1), instance of ArrayObject(1))"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 1107,
          "call": "GraphQL\\Executor\\ReferenceExecutor::collectAndExecuteSubfields(GraphQLType: Page, instance of ArrayObject(1), array(1), instance of WPGraphQL\\Model\\Post)"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 794,
          "call": "GraphQL\\Executor\\ReferenceExecutor::completeObjectValue(GraphQLType: Page, instance of ArrayObject(1), instance of GraphQL\\Type\\Definition\\ResolveInfo, array(1), instance of WPGraphQL\\Model\\Post)"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 652,
          "call": "GraphQL\\Executor\\ReferenceExecutor::completeValue(GraphQLType: Page, instance of ArrayObject(1), instance of GraphQL\\Type\\Definition\\ResolveInfo, array(1), instance of WPGraphQL\\Model\\Post)"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromise.php",
          "line": 148,
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(instance of WPGraphQL\\Model\\Post)"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromise.php",
          "line": 53,
          "call": "GraphQL\\Executor\\Promise\\Adapter\\SyncPromise::GraphQL\\Executor\\Promise\\Adapter\\{closure}()"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromiseAdapter.php",
          "line": 149,
          "call": "GraphQL\\Executor\\Promise\\Adapter\\SyncPromise::runQueue()"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Server/Helper.php",
          "line": 214,
          "call": "GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter::wait(instance of GraphQL\\Executor\\Promise\\Promise)"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Server/StandardServer.php",
          "line": 136,
          "call": "GraphQL\\Server\\Helper::executeOperation(instance of GraphQL\\Server\\ServerConfig, instance of GraphQL\\Server\\OperationParams)"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql/src/Request.php",
          "line": 602,
          "call": "GraphQL\\Server\\StandardServer::executeRequest(instance of GraphQL\\Server\\OperationParams)"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql/src/Router.php",
          "line": 465,
          "call": "WPGraphQL\\Request::execute_http()"
        },
        {
          "file": ".../app/public/wp-content/plugins/wp-graphql/src/Router.php",
          "line": 270,
          "call": "WPGraphQL\\Router::process_http_request()"
        },
        {
          "file": ".../app/public/wp-includes/class-wp-hook.php",
          "line": 292,
          "call": "WPGraphQL\\Router::resolve_http_request(instance of WP)"
        },
        {
          "file": ".../app/public/wp-includes/class-wp-hook.php",
          "line": 316,
          "call": "WP_Hook::apply_filters(null, array(1))"
        },
        {
          "file": ".../app/public/wp-includes/plugin.php",
          "line": 551,
          "call": "WP_Hook::do_action(array(1))"
        },
        {
          "file": ".../app/public/wp-includes/class-wp.php",
          "line": 388,
          "function": "do_action_ref_array('parse_request', array(1))"
        },
        {
          "file": ".../app/public/wp-includes/class-wp.php",
          "line": 750,
          "call": "WP::parse_request((empty string))"
        },
        {
          "file": ".../app/public/wp-includes/functions.php",
          "line": 1291,
          "call": "WP::main((empty string))"
        },
        {
          "file": ".../app/public/wp-blog-header.php",
          "line": 16,
          "function": "wp()"
        },
        {
          "file": ".../app/public/index.php",
          "line": 17,
          "function": "require('.../app/public/wp-blog-header.php')"
        }
      ]
    }
  ],
  "data": {
    "page": {
      "blocksJSON": null
    }
  },
  "extensions": {
    "debug": []
  }
}
```

**Comment by ojohnny** [comment] 2021-05-14 12:41
I have also seen strange behavior with wp-graphql-gutenberg and PHP 8. Today we tried to update an existing site to PHP 8, and queries for the page marked as "front page" stopped working.  All other pages seemed fine (although I'm not sure the other pages had been updated after the migration). The queries started working again after a downgrade to PHP 7.4.

**Comment by ojohnny** [comment] 2021-11-21 10:04
Since the support of PHP 7.4 is numbered ("active support" ends in less than a week, "security support" ends in a year), I decided to look into this a bit more.  The good news is that the only visible problem I can see right now is in one single line of code.  Fixing that fixes both the "paragraph with custom font size" described by @ravewebdev.  I also think it solves my problem, which I believe was actually the "Latest Posts" block crashing.

The situation seems to be that this message

```
get_object_vars(): Argument #1 ($object) must be of type object, array given
```

was a Warning in PHP 7.4 and has been promoted to a TypeError in PHP 8.0.  So there is a bug even when running PHP 7.4, although on the surface it seems to be able to handle it anyway.

The bug is on line 151 in `src/Blocks/Blocks.php` and occurs when `$attributes` is a nested array.  On the same line we do a cast to `(object)`, but this only converts the outer array, not the inner ones.  The validator seems to recursively call all items within `$attributes`, so to solve this bug we need to cast `$attributes` to objects recursively as well.

The simplest way I can figure out to do this is to encode it to JSON and back again (`json_decode(json_encode($attributes))`) which converts everything to an object, including nested arrays.  Not sure if there is a better way of doing it?

I can open a PR with this change if we think this is the way to solve it.

**Comment by kamilgrzegorczyk** [comment] 2022-01-18 07:17
Hey @pristas-peter thank you for the hard work on the plugin.
I have a question though - are there any plans for a new version release? That issue is quite important for all of us being on PHP8 and unless we want to hack a plugin and deploy unreleased version we have to rely on official release.
Do you have any date in mind?

Thanks

**Comment by rodrigo-arias** [comment] 2022-01-18 14:00
I just want to mention that I left a [comment](https://github.com/pristas-peter/wp-graphql-gutenberg/pull/129#issuecomment-1009480276) as this fix is breaking the innerBlocks attributes in PHP 7.4

**Comment by ojohnny** [comment] 2022-02-19 08:32
@rodrigo-arias Thanks for the clarification, I actually misread your comment the first time.  I thought you meant that innerBlocks were entirely broken, but I now see that you wrote that _attributes inside innerBlocks_ is the thing that becomes broken on your setup.

> Let me know if you can verify the same from your side.

I cannot see the same behavior on my side, I can still access `attributes` inside `innerBlocks`.  But I suppose that means that the problem may not be in the code, but that JSON for whatever reason is not available by default in your PHP installation?

Can you create a PHP file containing  `<?php phpinfo();` on your installation and check if JSON support is enabled?

![Screenshot from 2022-02-19 09-11-01](https://user-images.githubusercontent.com/6860386/154793127-2453f6c9-ed0a-4d28-a7c5-c26ac1b4d703.png)

It should be enabled by default on PHP ≥ 7 unless compiled with `--disable-json` (if your distribution did this you may have to install and enable a separate php7.4-json package I think).

[Quote from the JSON extension installation page:](https://www.php.net/manual/en/json.installation.php)
>  The JSON extension is bundled and compiled into PHP by default.
>
> As of PHP 8.0.0, the JSON extension is a core PHP extension, so it is always enabled.

Keep us updated if this is actually the problem.

**Comment by lmartins** [comment] 2022-03-18 15:32
Getting the same error in PHP 7.4. Looking at the information given back by `phpinfo` looks like JSON is enabled: 

![CleanShot 2022-03-18 at 15 32 29](https://user-images.githubusercontent.com/151981/159033389-d6cf5c65-2f98-4087-889b-3e0e8e3744cf.png)

**Comment by rodrigo-arias** [comment] 2022-03-18 18:37
@ojohnny sorry, I couldn't answer earlier. I checked the JSON support and it is enabled. The same thing happens locally or on in WP Engine. In any case, if it were disabled, I guess it wouldn't affect only part of the scheme. I'd think there is something wrong with the added parsing and the schema validator, I'll try to spend some time on it today.

**Comment by ojohnny** [comment] 2022-03-19 08:50
@lmartins @rodrigo-arias 

I looked at this some more, and I think I found two bugs related to this.

1. If `$attributes` is empty, then the conversion to an object does not really work.  For some reason it will still be an (empty) array, and I suppose this is what fails in PHP 7.4.  Am I correct to assume that you can read the attributes if you e.g. enable the "drop cap" setting on a paragraph? (in this case `$attributes` would not be empty anymore, since that setting is stored in the array and not in the HTML)
2. PHP ≥ 8.0 does not seem to like empty HTML strings when attempting to parse `innerHTML`.  This showed up after I attemted to fix (1), if the page contains e.g. a Latest Posts block with default settings.  The error I got in this scenario was `DOMDocument::loadHTML(): Argument #1 ($source) must not be empty`.

I think I have a working fix for both of these and I will make a pull request with my findings. If you have the time to test it that would be great.

**Comment by rodrigo-arias** [comment] 2022-03-21 21:07
@ojohnny thanks for working on this. Your explanation makes sense, I can confirm that the content was still there if I set any attributes and therefore it does not convert an empty array.

It seems that [JSON_FORCE_OBJECT](https://stackoverflow.com/questions/28189390/json-encode-function-not-return-braces-when-array-is-empty-in-php) is not an option in this case since a custom schema is used.

Also, some interesting notes on hit performance and UTF-8 data are mentioned [here](https://stackoverflow.com/a/1869147).

**Comment by pristas-peter** [comment] 2022-05-19 18:46
👍

**Closed by pristas-peter** 2022-05-19 18:46 UTC
