### ISSUE TITLE
Not working with wp-graphql version 1.4.0

### ISSUE THREAD

**Issue by shrenikTrukky** [pristas-peter/wp-graphql-gutenberg#111] opened 2021-06-16 07:06 UTC
Today when I upgrade my wp-graphql plugin from 1.3.9 to 1.4.0 . it stops working. and it's working fine with old version.

`query MyQuery {
  pages {
    nodes {
      blocks {
        order
        name
        __typename
        attributesJSON
      }
    }
  }
}
`

**Comment by aderaaij** [comment] 2021-06-16 16:07
Same here. Upgrading to WPGraphQL 1.4.0 makes the blocks disappear from the GraphiQL IDE as well. Downgrading to 1.3.9/1.3.10 works fine. I'll try and dig around a bit to see what the issue is but any help is greatly appreciated!

**Comment by aderaaij** [comment] 2021-06-16 16:28
Found the culprit - https://github.com/wp-graphql/wp-graphql/issues/1957. I think this needs to be fixed in the WPGraphQL plugin

**Comment by aderaaij** [comment] 2021-06-16 21:15
Should be fixed with the new WP GraphQL release https://github.com/wp-graphql/wp-graphql/releases/tag/v1.4.1

**Comment by shrenikTrukky** [comment] 2021-06-17 01:47
yes it's fixed in new version :)

**Closed** 2021-06-17 06:54 UTC
